# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: mjmm13/segway-test-build:latest

pipelines:
  default:
    - parallel:
        - step:
            caches:
              - pip
            name: Python2
            script:
              - pip install .
              - python --version
              - gmtkPrint -version
              - pip list 
              - cd test && ./test_all.sh
        - step:
            caches:
              - pip
            name: Python3
            script:
              - alias python="python3"
              - pip3 install .
              - python --version
              - gmtkPrint -version
              - pip3 list
              - cd test && ./test_all.sh
