version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: hoffmanlab/segway-test:latest
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache

workflows:
  main:
    jobs:
      - build
