name: Build and Test

# Workflow is triggered for every pull request on and push to any branch

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # Run job for both python versions in the docker image
    strategy:
      matrix:
        python-version: [2, 3]
    container:
      image: hoffmanlab/segway-test:latest
      env:
        SEGWAY_TEST_PYTHON_VERSION: ${{matrix.python-version}}

    steps:
      - uses: actions/checkout@v2
      - name: Build repository
        run: |
          python${SEGWAY_TEST_PYTHON_VERSION} -m pip install --verbose .
          pip list
      - name: Run tests
        run: |
          gmtkPrint -version
          cd test && ./test_all.sh
